CREATE SCHEMA `MY_CRM` ;

CREATE TABLE `MY_CRM`.`CUSTOMER` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100) NOT NULL,
  `DEPARTMENT` VARCHAR(50) NOT NULL,
  `ADDRESS` VARCHAR(200) NULL,
  `MOBILE` VARCHAR(20) NULL,
  `EMAIL` VARCHAR(50) NULL,
  `ACTIVE` TINYINT(1) NULL,
  `CREATED_TIME` BIGINT(14) NULL,
  `UPDATED_TIME` BIGINT(14) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC));

CREATE TABLE `MY_CRM`.`CUSTOMER_OPERATIONS` (
  `ID` INT(11) NOT NULL,
  `CUSTOMER_ID` INT(11) NOT NULL,
  `TIMESTAMP` BIGINT(14) NOT NULL,
  `OPERATION` VARCHAR(45) NOT NULL,
  `LOG` VARCHAR(150) NULL,
  PRIMARY KEY (`ID`));


ALTER TABLE `MY_CRM`.`CUSTOMER_OPERATIONS`
ADD INDEX `fk_CUSTOMER_OPERATIONS_1_idx` (`CUSTOMER_ID` ASC);
ALTER TABLE `MY_CRM`.`CUSTOMER_OPERATIONS`
ADD CONSTRAINT `fk_CUSTOMER_OPERATIONS_1`
  FOREIGN KEY (`CUSTOMER_ID`)
  REFERENCES `MY_CRM`.`CUSTOMER` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
