CREATE SCHEMA `MY_CRM` ;

CREATE TABLE `MY_CRM`.`CUSTOMER` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100) NOT NULL,
  `DEPARTMENT` VARCHAR(50) NOT NULL,
  `ADDRESS` VARCHAR(200) NULL,
  `MOBILE` VARCHAR(20) NULL,
  `EMAIL` VARCHAR(50) NULL,
  `ACTIVE` TINYINT(1) NULL,
  `CREATED_TIME` BIGINT(14) NULL,
  `UPDATED_TIME` BIGINT(14) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC));

CREATE TABLE `MY_CRM`.`LOG` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `TIMESTAMP` BIGINT(14) NOT NULL,
  `OPERATION` VARCHAR(45) NOT NULL,
  `LOG` VARCHAR(150) NULL,
  PRIMARY KEY (`ID`));
